<?php

/**
 * @file
 */

/**
 * Implementation of hook_views_data_alter().
 */
function rb_views_fields_views_data_alter(&$data) {
  // FIELDS.
  // $data['views']['quan_views_fields_content_lightbox'] = array(
  //   'title' => t('Lightbox and horizontal navigation'),
  //   'help' => t('Module quan_views_fields'),
  //   'group' => 'QUAN',
  //   'field' => array(
  //     'handler' => 'quan_views_fields_handler_show_lightbox',
  //   ),
  // );
}
